# Generated by Django 3.0.6 on 2020-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254, null=True)),
                ('phoneNo', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FeMale', 'FeMale')], max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
    ]
