# Generated by Django 3.0.6 on 2020-05-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200526_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phoneNo',
        ),
    ]
